networks:
    traefik-public:
        external: true
    cosmia-sav:
        external: true

services:
    sav-app:
        build: .
        container_name: sav-app
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - sav-storage:/var/www/html/storage
        networks:
            - cosmia-sav
            - traefik-public
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.sav.rule=Host(`sav.astucom.com`)
            - traefik.http.routers.sav.entrypoints=websecure
            - traefik.http.routers.sav.tls.certresolver=letsencrypt
            - traefik.http.services.sav.loadbalancer.server.port=80

volumes:
    sav-storage:
